# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='need_subscribers',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
