# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_need_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='anonymous_subscribers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
