# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_event_lector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['pub_date']},
        ),
        migrations.AlterField(
            model_name='event',
            name='anonymous_subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
